<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <DocumentationFile>.\TemplateApi.Teste.xml</DocumentationFile>
      <NoWarn>1701;1702;1591;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DocumentationFile>.\TemplateApi.Teste.xml</DocumentationFile>
      <NoWarn>1701;1702;1591;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.23" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api\TemplateApi.Api.csproj" />
    <ProjectReference Include="..\src\TemplateApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
      <Folder Include="storage\public\" />
      <Folder Include="storage\private\" />
  </ItemGroup>

    <ItemGroup>
        <None Update="assets\.gitkeep">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="storage\public\.gitkeep">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="storage\private\.gitkeep">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
