//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.API.Template.RecursoResx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AvisosResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvisosResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore.API.Template.RecursoResx.AvisosResx", typeof(AvisosResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceso não autenticado..
        /// </summary>
        public static string AcessoNaoAutenticado {
            get {
                return ResourceManager.GetString("AcessoNaoAutenticado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado..
        /// </summary>
        public static string AcessoNaoAutorizado {
            get {
                return ResourceManager.GetString("AcessoNaoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chave pública não foi recebida..
        /// </summary>
        public static string ChavePublicaNaoRecebiada {
            get {
                return ResourceManager.GetString("ChavePublicaNaoRecebiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato inválido..
        /// </summary>
        public static string FormatoInvalido {
            get {
                return ResourceManager.GetString("FormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode ser nulo..
        /// </summary>
        public static string NaoPodeSerNulo {
            get {
                return ResourceManager.GetString("NaoPodeSerNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro interno na solicitação..
        /// </summary>
        public static string OcorreuUmErroInterno {
            get {
                return ResourceManager.GetString("OcorreuUmErroInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso do arquivo deve ser menou ou iqual a {0} kb..
        /// </summary>
        public static string PesoDoArquivoEmKbInvalido {
            get {
                return ResourceManager.GetString("PesoDoArquivoEmKbInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter um de cada dos conjuntos  [0-9], [A-Z], [a-z] e [-_$%#@!*.+=]..
        /// </summary>
        public static string SenhaDeveConter {
            get {
                return ResourceManager.GetString("SenhaDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na solicitação..
        /// </summary>
        public static string SolicitacaoErro {
            get {
                return ResourceManager.GetString("SolicitacaoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação não autorizada..
        /// </summary>
        public static string SolicitacaoNaoAutorizada {
            get {
                return ResourceManager.GetString("SolicitacaoNaoAutorizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação realizada com sucesso..
        /// </summary>
        public static string SolicitacaoSucesso {
            get {
                return ResourceManager.GetString("SolicitacaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação realizada com sucesso..
        /// </summary>
        public static string Status200 {
            get {
                return ResourceManager.GetString("Status200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu algum erro na solicitação..
        /// </summary>
        public static string Status400 {
            get {
                return ResourceManager.GetString("Status400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação não autorizada..
        /// </summary>
        public static string Status401 {
            get {
                return ResourceManager.GetString("Status401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro interno na solicitação..
        /// </summary>
        public static string Status500 {
            get {
                return ResourceManager.GetString("Status500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os tipos de arquivos permitidos são imagens, textos ou planilas..
        /// </summary>
        public static string TipoDeArquivoStorageInvalido {
            get {
                return ResourceManager.GetString("TipoDeArquivoStorageInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo inválido..
        /// </summary>
        public static string TipoInvalido {
            get {
                return ResourceManager.GetString("TipoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token de autenticação não foi recebido..
        /// </summary>
        public static string TokenDeAutenticacaoNaoRecebido {
            get {
                return ResourceManager.GetString("TokenDeAutenticacaoNaoRecebido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor não está no formato válido..
        /// </summary>
        public static string ValorNoFormatoInvalido {
            get {
                return ResourceManager.GetString("ValorNoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de &quot;{0}&quot; é obrigatório. .
        /// </summary>
        public static string XHeObrigatorio {
            get {
                return ResourceManager.GetString("XHeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de {0} não é únido..
        /// </summary>
        public static string XNaoEhUnico {
            get {
                return ResourceManager.GetString("XNaoEhUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não é válido(a)..
        /// </summary>
        public static string XNaoEhValido {
            get {
                return ResourceManager.GetString("XNaoEhValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrado(a)..
        /// </summary>
        public static string XNaoEncontrado {
            get {
                return ResourceManager.GetString("XNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrados(as)..
        /// </summary>
        public static string XNaoEncontrados {
            get {
                return ResourceManager.GetString("XNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propriedade &quot;{0}&quot; ainda não foi configurada..
        /// </summary>
        public static string XPropriedadeNaoConfigurada {
            get {
                return ResourceManager.GetString("XPropriedadeNaoConfigurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve conter um de cada dos conjuntos  [0-9], [A-Z], [a-z] e [-_$%#@!*.+=]..
        /// </summary>
        public static string XSenhaDeveConter {
            get {
                return ResourceManager.GetString("XSenhaDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de &quot;{0}&quot; não pode ser vazio..
        /// </summary>
        public static string XValorNaoPodeSerVazio {
            get {
                return ResourceManager.GetString("XValorNaoPodeSerVazio", resourceCulture);
            }
        }
    }
}
