//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.API.Template.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AvisosResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvisosResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore.API.Template.Recurso.AvisosResx", typeof(AvisosResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado..
        /// </summary>
        public static string AcessoNaoAutorizado {
            get {
                return ResourceManager.GetString("AcessoNaoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro interno na solicitação..
        /// </summary>
        public static string OcorreuUmErroInterno {
            get {
                return ResourceManager.GetString("OcorreuUmErroInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na solicitação..
        /// </summary>
        public static string SolicitacaoErro {
            get {
                return ResourceManager.GetString("SolicitacaoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação não autorizada..
        /// </summary>
        public static string SolicitacaoNaoAutorizada {
            get {
                return ResourceManager.GetString("SolicitacaoNaoAutorizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação realizada com sucesso..
        /// </summary>
        public static string SolicitacaoSucesso {
            get {
                return ResourceManager.GetString("SolicitacaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de &quot;{0}&quot; é obrigatório. .
        /// </summary>
        public static string XHeObrigatorio {
            get {
                return ResourceManager.GetString("XHeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de {0} não é únido..
        /// </summary>
        public static string XNaoEhUnico {
            get {
                return ResourceManager.GetString("XNaoEhUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não é válido(a)..
        /// </summary>
        public static string XNaoEhValido {
            get {
                return ResourceManager.GetString("XNaoEhValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrado(a)..
        /// </summary>
        public static string XNaoEncontrado {
            get {
                return ResourceManager.GetString("XNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrados(as)..
        /// </summary>
        public static string XNaoEncontrados {
            get {
                return ResourceManager.GetString("XNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propriedade &quot;{0}&quot; ainda não foi configurada..
        /// </summary>
        public static string XPropriedadeNaoConfigurada {
            get {
                return ResourceManager.GetString("XPropriedadeNaoConfigurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de &quot;{0}&quot; não pode ser vazio..
        /// </summary>
        public static string XValorNaoPodeSerVazio {
            get {
                return ResourceManager.GetString("XValorNaoPodeSerVazio", resourceCulture);
            }
        }
    }
}
